<?php
$users = array(
				'jv6dmc' =>array(
								'nom' => "Mc Clure",
								'prenom' => "Nicolas",
								'email' => 'nicolas.mcclure@hotmail.ca',
								'password'=> '1234',
								'favoris' => array(
												'prod01',
                        'prod03',
                        'prod04'
												)
						    ),
          'briou' =>array(
								'nom' => "Riou",
								'prenom' => "Brice",
								'email' => 'briou69@gmail.ca',
								'password'=> '4321',
								'favoris' => array(
												'prod01',
                        'prod03',
                        'prod04'
												)
							)
					); 
          
          

?>