<?php
$etudiants = array(
				'123456789' =>array(
									'nom' => "Jean0",
									'prenom' => "Phillipe",
									'groupe' => "GR-11",
									'email' => 'etudiant1@gmail.com',
									'dateinscription'=> '2013/04/02',
									'password'=> '123',

									'notes' => array(
													'ASP'=>55.6,
													'PHP' => 62,
													'Java' => 45.6,
													'C++' => 77.9,
													'Javascript'=>82.4,
													'HTML' => 88
													)
										),
				'883556789' =>array(
								'nom' => "Jean1",
								'prenom' => "Phillipe",
								'groupe' => "GR-11",
								'email' => 'etudiant2@gmail.com',
								'dateinscription'=> '2013/04/06',
								'password'=> '123',

								'notes' => array(
												'ASP'=>55.6,
												'PHP' => 62,
												'Java' => 45.6,
												'C++' => 77.9,
												'Javascript'=>82.4,
												'HTML' => 88
												)

							),
				'999888666' =>array(
								'nom' => "Jean2",
								'prenom' => "Phillipe",
								'groupe' => "GR-11",
								'email' => 'nicolas.mcclure@hotmail.ca',
								'dateinscription'=> '2013/02/06',
								'password'=> '1234',

								'notes' => array(
												'ASP'=>55.6,
												'PHP' => 62,
												'Java' => 45.6,
												'C++' => 77.9,
												'Javascript'=>82.4,
												'HTML' => 88
												)

							)



					); 
?>